import { NextResponse } from "next/server"

export async function GET() {
  // Ces données seraient normalement récupérées depuis une base de données
  const adminUsersData = {
    users: [
      {
        id: "user_001",
        name: "Marie Dubois",
        email: "marie.dubois@email.com",
        type: "buyer",
        status: "active",
        registeredAt: "2024-01-10T10:30:00Z",
        lastLogin: "2024-01-15T09:15:00Z",
        totalOrders: 23,
        totalSpent: 1456.78,
        verified: true,
        location: "Paris, France",
      },
      {
        id: "user_002",
        name: "Ferme Martin",
        email: "contact@ferme-martin.fr",
        type: "seller",
        status: "active",
        registeredAt: "2023-12-05T14:20:00Z",
        lastLogin: "2024-01-15T08:45:00Z",
        totalProducts: 45,
        totalSales: 12456.89,
        verified: true,
        location: "Normandie, France",
        subscription: "Premium",
      },
      {
        id: "user_003",
        name: "Jean Dupont",
        email: "jean.dupont@email.com",
        type: "buyer",
        status: "suspended",
        registeredAt: "2024-01-08T16:45:00Z",
        lastLogin: "2024-01-12T11:30:00Z",
        totalOrders: 5,
        totalSpent: 234.56,
        verified: false,
        location: "Lyon, France",
        suspensionReason: "Paiements frauduleux détectés",
      },
      {
        id: "user_004",
        name: "Ferme Bio Leclerc",
        email: "bio@leclerc-ferme.com",
        type: "seller",
        status: "pending",
        registeredAt: "2024-01-14T12:00:00Z",
        lastLogin: "2024-01-15T07:30:00Z",
        totalProducts: 12,
        totalSales: 2345.67,
        verified: false,
        location: "Bretagne, France",
        subscription: "Basic",
      },
      {
        id: "user_005",
        name: "Sophie Laurent",
        email: "sophie.laurent@email.com",
        type: "buyer",
        status: "active",
        registeredAt: "2023-11-20T09:15:00Z",
        lastLogin: "2024-01-15T10:45:00Z",
        totalOrders: 67,
        totalSpent: 3456.78,
        verified: true,
        location: "Marseille, France",
      },
      {
        id: "user_006",
        name: "Maraîchage Durand",
        email: "contact@durand-maraichage.fr",
        type: "seller",
        status: "active",
        registeredAt: "2023-10-15T11:30:00Z",
        lastLogin: "2024-01-15T06:20:00Z",
        totalProducts: 78,
        totalSales: 23456.78,
        verified: true,
        location: "Provence, France",
        subscription: "Premium",
      },
    ],
    pendingProducts: [
      {
        id: "prod_pending_001",
        name: "Tomates cerises biologiques",
        seller: "Ferme Martin",
        sellerId: "user_002",
        category: "Légumes",
        price: 4.5,
        submittedAt: "2024-01-15T10:30:00Z",
        status: "pending",
        images: 5,
        description: "Tomates cerises cultivées sans pesticides, récoltées à maturité parfaite.",
      },
      {
        id: "prod_pending_002",
        name: "Miel de lavande artisanal",
        seller: "Rucher Provence",
        sellerId: "user_007",
        category: "Produits de la ruche",
        price: 12.9,
        submittedAt: "2024-01-15T09:45:00Z",
        status: "pending",
        images: 3,
        description: "Miel de lavande récolté dans les champs de Provence, 100% naturel.",
      },
      {
        id: "prod_pending_003",
        name: "Fromage de chèvre fermier",
        seller: "Chèvrerie des Alpes",
        sellerId: "user_008",
        category: "Produits laitiers",
        price: 8.75,
        submittedAt: "2024-01-15T08:20:00Z",
        status: "pending",
        images: 4,
        description: "Fromage de chèvre affiné 3 semaines, fabriqué à la ferme selon des méthodes traditionnelles.",
      },
      {
        id: "prod_pending_004",
        name: "Pommes Golden bio",
        seller: "Verger du Soleil",
        sellerId: "user_009",
        category: "Fruits",
        price: 3.2,
        submittedAt: "2024-01-14T16:15:00Z",
        status: "pending",
        images: 6,
        description: "Pommes Golden cultivées en agriculture biologique, croquantes et sucrées.",
      },
    ],
  }

  return NextResponse.json(adminUsersData)
}
